import random

LOVE_STICKERS = [
'CAACAgIAAxkBAAEGevBjekBaV96xaZLu1XKiG02DgJKcQgAClAADO2AkFN_Z17VvZiksKwQ', 
'CAACAgIAAxkBAAEGgk9jfQWsGxR9SGfE5J0zogJ4Q7ueKQACGgMAAs7Y6AuWbFhY5IoBjCsE', 
'CAACAgIAAxkBAAEGglFjfQW8QG4dFGxw2scnl-Zlkm8yAAMWAQACECECEO3Wsw2mfvkYKwQ', 
'CAACAgIAAxkBAAEGglNjfQXV-8H8TwYdaW0orvQZlps0yAACowADO2AkFEbAuxT8FVuKKwQ', 
'CAACAgIAAxkBAAEGglVjfQXk-qnhA9-NgxnXmg1eVYTskwACtQAD9wLIDzOvqyodfzZvKwQ', 
'CAACAgIAAxkBAAEGgldjfQXw8oNVdI6yTdgEDV0ydXcMhwACzwAD9wLID7n4OPunGK79KwQ', 
'CAACAgIAAxkBAAEGglljfQYGD2VcburIakt4nwYwXr1dNQACewADwZxgDNsaH7YdVDaIKwQ', 
'CAACAgIAAxkBAAEGgl5jfQYUyuC5nbOdKjax2jPOT-Qk-wACLgAD7sShCrt3SNkt-wsLKwQ', 
'CAACAgIAAxkBAAEGgmRjfQY0Cyer_rtCCwyydn_5G60B2QACpQUAAj-VzApWUPAuKhZedSsE', 
'CAACAgIAAxkBAAEGgmZjfQZHiAtq8bsH0QbtqVnCLiGF0QACWhIAAu4_4Us2E8GNf5X65CsE', 
'CAACAgIAAxkBAAEGgmhjfQZXK0kCzQ4GRXibY5WQLTDRJAAC7xQAAjsiSEgO0Yc9P0OZ_CsE', 
'CAACAgIAAxkBAAEGgmpjfQZhNkQxWcLRmwjYszoTLryo-AAChBwAApom4UtpTBJ3IoaoLisE', 
'CAACAgIAAxkBAAEGgmxjfQZwsCqnHCerpMpGDDo-Jb9FXAACAgADO2AkFKDCS3QQPmUeKwQ', 
'CAACAgIAAxkBAAEGgm5jfQaBuYkrc3eo7MflbJDXA9DV3QACggQAAucXqAJAAdmFCIrX1ysE', 
'CAACAgIAAxkBAAEGgnBjfQaMZGQx5IAgkPXEmE-F8WCr1AACVAEAAjDUnRE1EWvwoCBW6ysE'
]

def random_love_sticker():
    choice = random.choice(LOVE_STICKERS)
    return choice